### PR TITLE
upgrade api instances to xlarge

### PR DESCRIPTION
**Pull request by andrewelamb**
- Adds `r5.xlarge` to allowable instances sizes
- Changes API (prod and staging instnaces) to `r5.xlarge`

### CODE REVIEW

**Comment by andrewelamb** [comment]
@xschildw It looks like Travis is faling here.

**Review by ConsoleCatzirl — CHANGES_REQUESTED** [review]
I think the error is caused by the removal of `setup_aws_cli.sh` in Sage-Bionetworks/infra-utils#59 and the preferred solution is to convert to github actions with a change similar to Sage-Bionetworks/agora2-infra#18

**Comment by andrewelamb** [comment]
@jesusaurus Thansk for the reply! What would an ETA look like for this?

**Comment by ConsoleCatzirl** [comment]
@andrewelamb I'm suggesting to migrate this repo from travis to github actions, similar to the migration in the agora2 PR I linked. If you need help with that migration, can you open an IT ticket in jira for the team to triage?

**Comment by andrewelamb** [comment]
@jesusaurus Yes we need that migration done ASAP. I'm curious why the script that this repo needs was deleted without any heads up to anyone on the iAtlas team, or just doing the migration here as well.

**Comment by andrewelamb** [comment]
Alternatively the script could be restored so we cna get this and [another PR](https://github.com/Sage-Bionetworks/iAtlas-infra/pull/66) working.

**Comment by andrewelamb** [comment]
I've created an issue [here](https://sagebionetworks.jira.com/browse/IT-3733)

**Pull request merged**
